/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9ae6275b-b804-4708-8567-dc4b82c51512",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_iXYiUMcw6",
    "aws_user_pools_web_client_id": "419bij73ku10afv6ane8j9vru4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://vxt5ovlog5c3pccgjqyzq3dgqy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "orderlambda",
            "endpoint": "https://4r87r93xyd.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_user_files_s3_bucket": "amplifytianguis18a162aa664f47fa94ac5c6c7665466903859-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
